# This function was generated by ArmorstandAnimator
execute if score @s AsaMatrix matches 1 run execute if entity @e[tag=kuronoa] run playsound entity.cat.ambient master @a 41.0 82.0 -33.0 3.0 1.0 1.0
scoreboard players add @s AsaMatrix 1
execute if score @s AsaMatrix matches 1 run function asa_animator:mochkun/mochtuch/start
execute if score @s AsaMatrix matches 1 run function asa_animator:mochkun/mochtuch/keyframes/0
execute if score @s AsaMatrix matches 1..8 run tp @s ^0 ^0 ^0
execute if score @s AsaMatrix matches 9 run function asa_animator:mochkun/mochtuch/quick_/1_0
execute if score @s AsaMatrix matches 10 run function asa_animator:mochkun/mochtuch/quick_/1_1
execute if score @s AsaMatrix matches 11 run function asa_animator:mochkun/mochtuch/quick_/1_2
execute if score @s AsaMatrix matches 12 run function asa_animator:mochkun/mochtuch/quick_/1_3
execute if score @s AsaMatrix matches 9..12 run tp @s ^0 ^0 ^0
execute if score @s AsaMatrix matches 13 run function asa_animator:mochkun/mochtuch/keyframes/2
execute if score @s AsaMatrix matches 13..16 run tp @s ^0 ^0 ^0
execute if score @s AsaMatrix matches 17 run function asa_animator:mochkun/mochtuch/keyframes/3
execute if score @s AsaMatrix matches 17..20 run tp @s ^0 ^0 ^0
execute if score @s AsaMatrix matches 21 run function asa_animator:mochkun/mochtuch/keyframes/4
execute if score @s AsaMatrix matches 21..22 run tp @s ^0 ^0 ^0
execute if score @s AsaMatrix matches 23 run function asa_animator:mochkun/mochtuch/keyframes/5
execute if score @s AsaMatrix matches 23..24 run tp @s ^0 ^0 ^0
execute if score @s AsaMatrix matches 25 run function asa_animator:mochkun/mochtuch/keyframes/6
execute if score @s AsaMatrix matches 25..25 run tp @s ^0 ^0 ^0
execute if score @s AsaMatrix matches 26 run function asa_animator:mochkun/mochtuch/keyframes/7
execute if score @s AsaMatrix matches 26..33 run tp @s ^0 ^0 ^0
execute if score @s AsaMatrix matches 34 run function asa_animator:mochkun/mochtuch/keyframes/8
execute if score @s AsaMatrix matches 34..37 run tp @s ^0 ^0 ^0
execute if score @s AsaMatrix matches 38 run function asa_animator:mochkun/mochtuch/keyframes/9
execute if score @s AsaMatrix matches 38..41 run tp @s ^0 ^0 ^0
execute if score @s AsaMatrix matches 42 run function asa_animator:mochkun/mochtuch/keyframes/10
execute if score @s AsaMatrix matches 42..43 run tp @s ^0 ^0 ^0
execute if score @s AsaMatrix matches 44 run function asa_animator:mochkun/mochtuch/keyframes/11
execute if score @s AsaMatrix matches 44..45 run tp @s ^0 ^0 ^0
execute if score @s AsaMatrix matches 46 run function asa_animator:mochkun/mochtuch/keyframes/12
execute if score @s AsaMatrix matches 46..49 run tp @s ^0 ^0 ^0
execute if score @s AsaMatrix matches 50 run function asa_animator:mochkun/mochtuch/keyframes/13
execute if score @s AsaMatrix matches 50..54 run tp @s ^0 ^0 ^0
execute if score @s AsaMatrix matches 55 run function asa_animator:mochkun/mochtuch/keyframes/14
execute if score @s AsaMatrix matches 55..58 run tp @s ^0 ^0 ^0
execute if score @s AsaMatrix matches 59 run function asa_animator:mochkun/mochtuch/keyframes/15
execute if score @s AsaMatrix matches 59..62 run tp @s ^0 ^0 ^0
execute if score @s AsaMatrix matches 63 run function asa_animator:mochkun/mochtuch/keyframes/16
execute if score @s AsaMatrix matches 63..66 run tp @s ^0 ^0 ^0
execute if score @s AsaMatrix matches 67 run function asa_animator:mochkun/mochtuch/keyframes/17
execute if score @s AsaMatrix matches 67..70 run tp @s ^0 ^0 ^0
execute if score @s AsaMatrix matches 71.. run function asa_animator:mochkun/mochtuch/end
execute as @e[type=armor_stand,tag=mochkunParts] run function #asa_matrix:animate
function asa_animator:mochkun/model
